function areaName = getNameFromAreaIndex_SteinMetz(areaIdx)

areaRef = [{...
    698, 'OLF';...
    654, 'PL';...
    985, 'MOp'; ...
    993, 'MOs'; ...
     31, 'ACA'; ...
     37, 'SSp';...
     


end